globals:
  users: 10000
  batch_size: 1000

up:

  - name: create_user
    query: |-
      CREATE TABLE IF NOT EXISTS "user" (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        email STRING NOT NULL,
        phone STRING,
        bio STRING,
        referred_by UUID
      )

seed:

  - name: populate_user
    type: exec_batch
    count: users
    size: batch_size
    args:
      - gen('email')
      - nullable(gen('phone'), 0.3)
      - nullable(gen('sentence:5'), 0.5)
      - nullable(uuid_v4(), 0.8)
    query: |-
      INSERT INTO "user" (email, phone, bio, referred_by)
      __values__

deseed:

  - name: truncate_user
    type: exec
    query: TRUNCATE TABLE "user"

down:

  - name: drop_user
    type: exec
    query: DROP TABLE IF EXISTS "user"
